package com.persoff68.fatodo.model.constant;

public enum WsEventType {

    ITEM_GROUP_CREATE,
    ITEM_GROUP_UPDATE,
    ITEM_GROUP_DELETE,
    ITEM_CREATE,
    ITEM_UPDATE,
    ITEM_UPDATE_STATUS,
    ITEM_UPDATE_ARCHIVED,
    ITEM_DELETE,
    ITEM_MEMBER_ADD,
    ITEM_MEMBER_DELETE,
    ITEM_MEMBER_LEAVE,
    ITEM_MEMBER_ROLE,

}
